# Generated by Django 3.0 on 2026-09-07 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
        ('profiles', '0002_copy_data'),   # drop ONLY after the data is copied
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
